
services:
  lab-nodered:
    restart: always
    user: "${UID}:${GID}"
    image: nodered/node-red:latest
    hostname: lab-nodered
    container_name: lab-nodered
    
    network_mode: host

    volumes:
      - ./nodered/data:/data:rw

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"